// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID      string `json:"id"`
	UserID  string `json:"userId"`
	Balance int    `json:"balance"`
}

type User struct {
	ID      string   `json:"id"`
	Account *Account `json:"account"`
}

func (User) IsEntity() {}
